name: Build

on:
  push:
    branches:
      - main
      # - checkActions

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ROLE_ARN }}
        aws-region: ${{ secrets.REGION }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

    - name: Deploy
      run: aws s3 sync dist/ s3://${BUCKET_NAME} --exact-timestamps --region ${REGION}
      env: 
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        REGION: ${{ secrets.REGION }}
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - name: Clear cache
    #   run: |
    #     aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"
    #   env:
    #     DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

